CREATE TABLE user
(
    id           int generated by default as identity primary key,
    user_name    varchar(100),
    password     varchar(100),
    user_role_id int,
    profile_id   int
);

create table incident
(
    id                  int generated by default as identity primary key,
    serviceName         varchar(100),
    is_active           boolean,
    problem_description varchar(300),
    user_id             int
);

create table user_role
(
    id               int generated by default as identity primary key,
    role_name        varchar(30),
    role_description varchar(200)
);

create table user_services
(
    service_id int primary key,
    user_id    int primary key
);

create table profile
(
    id           int generated by default as identity primary key,
    first_name   varchar(100),
    last_name    varchar(100),
    email        varchar(100),
    phone_number varchar(20),
    postal_code  varchar(20)
);

create table service
(
    id                  int generated by default as identity primary key,
    service_name        varchar(100),
    is_active           boolean,
    serivce_month_price float,
    customer_id         int
);

alter table user
    add constraint fk_profile_id foreign key (profile_id) references profile (id) on delete cascade;
alter table incident
    add constraint fk_user_id foreign key (user_id) references user (id) on delete cascade;
alter table user
    add constraint fk_user_role_id foreign key (user_role_id) references user_role (id) on delete set null;
alter table user
    add constraint fk_user_role_id foreign key (user_role_id) references user_role (id) on delete cascade;
alter table user_services
    add constraint fk_user_service_id foreign key (user_id) references user (id) on delete no action;
alter table user_services
    add constraint fk_service_id foreign key (service_id) references service (id) on delete no action;

