CREATE TABLE "user"
(
    id           int generated by default as identity primary key,
    user_name    varchar(100),
    password     varchar(100),
    user_role_id int ,
    profile_id   int unique
);

create table incident
(
    id                  int generated by default as identity primary key,
    service_name        varchar(100),
    is_active           boolean,
    problem_description varchar(300),
    user_id             int
);

create table user_role
(
    id               int generated by default as identity primary key,
    role_name        varchar(30),
    role_description varchar(200)
);

create table user_services
(
    service_id int,
    user_id    int
);

create table profile
(
    id           int generated by default as identity primary key,
    first_name   varchar(100),
    last_name    varchar(100),
    email        varchar(100),
    phone_number varchar(20),
    postal_code  varchar(20)
);

create table service
(
    id                  int generated by default as identity primary key,
    service_name        varchar(100),
    is_active           boolean,
    service_month_price float,
    customer_id         int
);



